language: ruby
rvm:
- 2.5.0
before_install: gem install bundler -v 2.0.2
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: CdvvtNSyOSkYgfHHo3x8w4WZhTrq9Ndx+4FiWOLrJNM10YmdNFeZTGtu78GFGC50lQqmzGyoYWQAaGofnKxx6u+NQR85PzFtzIrU5ZtOtVnB8/NrKcKDkixgu1i5ba2wNw/SxcrMbSAxwzmG9K6u07aM9EAbubUjP7Wp6jRZJd7pCr+RaAHOYPhaYzfNa5vS7m1xBT3fWCVOzGy0+JjOSoJ+X/h+Pve6lyErx/s0yQyGYvgwZ6O6hRCGI/Ns3dX20n6EneY5lWkHNnuSbcKXGcWJfmZm9TqrCeofp8xF3SxwDFAL0b+zDeUZ0HZtrhsAcc8UtqqISRfBRVPVF5DewrhyQtNH841mIbfnbKSLGfDT2AJb9aBPQV6kQOYvd/H3YGB0gp46tRXle7ZbuqKhTEwfLDAcGC5BKyhDbvFDI3SEjY3Rq+Dd+bfwgBrJ1or4iSKu7WY4VS7vAU2CiX3fe5+Kj4P6gu46VwoI+kc6YBTlKefftpdW4+CtGaza0hj5uuEQ6vAtrcNE8Jm1exv0t5GtlsJKBH+NC0/fE/uyn65Z4pOmaAvmbaE6o/j6nRaZyMgcvp1OBwuFbG0eMhu6FHlwkStLtu8SPgvakgX6NMO+IunXe5xjxZvgF21QNQSh5icqc4x98Kge2arCI87Cby9/nAxOosGiVQ5kLlPuSW8=
  app: api-penpal-boost
  on:
    repo: Not-Zorro/penpal_api
