language: ruby
rvm:
- 2.5.0
before_install: gem install bundler -v 2.0.2
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: EjFlWfdYvdACbD3z8xB5fv5NqEKCN1UcV94cFhMscXjSpNW1+GEEsZ9oLRqv+flYXEIfxoVhvKDrbYB1wOWmarrYyMajKmk6qs2s4UTBWmtAPtj7G46wcqI+CAAWoOZoBXFN5GIAkuINlEchS3E4HSzQMqWJ79Jc+Y4KYLumDeYYL85tyM1zg7C/1TZXyr1j0A6qHJAGjG2QU7hBiaAEYHSju5cKw5bvnp36vJsNx5a+IaboDfRN23le2TBqwa5LUwyBH8I6g04cgIc1KYGAmgaF0ZcJ7sW8MoTRODBdxOf2stHZDf0kXMYzpkmEnTMdwFqQT8BcIfcJoMbuQJMd45dhSkIDnJSrHgg/02yEY1DBB7afhHE1SIHcc+fEWHJyywjyeC6jznCahN4FBYQQyVHXAtRW/Yp6klz5seBkgqtOuLEjj+MTDb93H5ikkx7tfLrY2FlbS87RsiL3kCTH+IHrfQOMzPT2Pox5ly2CU5QCCF36n0y1g9SC/EUUhviUdwsphWSp8UQMTaSKarL/xOE2PUsZoyQbfoRyHaSiH0iFsKp2Ylni1Dde0lY8W9pCFTE5xnOOcstNUWAh5GvGafYTknWR2w1dkDufPjG/aWcjvwpiOy+a3w8nz0RHf8pOttHsT4Cn65MmmxsXC0IKvMfuGGQ6N1KG02gKzi2Htsc=
    app: api-penpal-boost
    on:
      repo: Not-Zorro/penpal_api
